### ISSUE TITLE
Event Window from ghostfur

### ISSUE THREAD

**Issue by Falke3434** [AionGermany/aion-germany#34] opened 2018-06-11 15:08 UTC
Not working!? (rev125)
- i can't see or open this Event Window

**Comment by ghostfur** [comment] 2018-06-11 15:13
Ow i will have a look falke because i was using it couple min ago with german release

**Comment by ghostfur** [comment] 2018-06-11 15:39
![131](https://user-images.githubusercontent.com/13853736/41241895-64122da2-6d9e-11e8-9085-c2f7c5a86b76.PNG)

**Comment by FrozenKiller35** [comment] 2018-06-11 15:42
Tested yesterday on GF-Server and it was disabled there 😞 maybe they changed something on Client files

**Comment by ghostfur** [comment] 2018-06-11 15:52
I also using GF Server + Client from steam did you try make new character ? to see if it get event window

**Comment by FrozenKiller35** [comment] 2018-06-11 16:04
I dont use Stean version only GF with GF launcher ^^ and no i didnt try to make a new char

**Comment by ghostfur** [comment] 2018-06-11 16:07
Because it import something in database when you make a new character i couldnt find alot about this event on internet so not sure exactly for now i set 3 times kinah in the event !

**Comment by benas80** [comment] 2018-06-11 16:53
Events show on GS console, but Event window not showed in client. (GF client used)

**Comment by ghostfur** [comment] 2018-06-11 17:35
Ow strange i thought gf and steam gf using same client version i will try download normal GF and see what happens 
![134](https://user-images.githubusercontent.com/13853736/41247568-9df8bada-6dae-11e8-89f0-ecdb24a285d4.PNG) What happens when you click event here?

**Comment by benas80** [comment] 2018-06-11 17:48
Yes, i checked this situation to.
Only shows comment in chat window: "There is no event for You to take a part in at the moment"
And nothing happens.

**Comment by ghostfur** [comment] 2018-06-11 17:58
Thanks! i will check gameforge client i almost got it maby they using different packet structure or opcode

**Comment by benas80** [comment] 2018-06-12 18:21
Ghost, did You found why this Event Window don't show up ?

**Comment by ghostfur** [comment] 2018-06-12 18:28
Hi there iam working on it right now! because here i also suddently dont see it anymore :)  so i running some tests

**Comment by ghostfur** [comment] 2018-06-12 18:52
Can you test the 2 new things at pull request to see what it does for you!

**Comment by FrozenKiller35** [comment] 2018-06-12 20:44
No time today but tomorrow ;)
But ghostfur take a look @ PlayerEventsWindowDAO.java (var1,var2, var3 realy ? 😜 )
Dont know if changed yet but also in PlayerEventWindowList.java (boolean add: RemaininG should be eventId 🤔 ) or SM_EVENT_WINDOW should be cleaned and and and 👅👅👅

It would be nice if you can clean and fix (vars) the whole code becomes cleaner and easier to fix if something heapens 😉 

But for now THX

**Comment by ghostfur** [comment] 2018-06-12 21:15
Yes i will do tomorrow if i have free time! still need to clean it all out it was for testing purpose but worked so far haha 🔢

**Comment by ghostfur** [comment] 2018-06-13 14:59
Iam home will work on it now!

**Comment by benas80** [comment] 2018-06-13 15:07
I don't see this icon. I this Event Window icon ?

![41310124-e8384e8a-6e80-11e8-8d21-cafe58aa14d9](https://user-images.githubusercontent.com/9912071/41360010-0a788f7c-6f2c-11e8-9e46-ba94dab1d7f8.PNG)

**Comment by ghostfur** [comment] 2018-06-13 15:35
![1516](https://user-images.githubusercontent.com/13853736/41361741-13ae5b90-6f30-11e8-9193-b0d4eac9a620.PNG) The first icon you see is for event window!

**Comment by benas80** [comment] 2018-06-13 15:35
How to test this premium service ? (how to show this icon)

**Comment by benas80** [comment] 2018-06-13 15:36
So this event icon and premium icon are not showing.

**Comment by ghostfur** [comment] 2018-06-13 15:37
Add -f2p to your launcher  its from free 2 play account grade stuff
![123](https://user-images.githubusercontent.com/13853736/41361915-79fecc40-6f30-11e8-860c-5ded34dc3a1d.png)

**Comment by benas80** [comment] 2018-06-13 15:39
Ok, im testing

**Comment by ghostfur** [comment] 2018-06-13 16:06
Iam cleaning event window now also adding orginal item content so should be done in 1/2 hours or less!

**Comment by ghostfur** [comment] 2018-06-13 18:46
I need todo something now sorry i will be back in 1/2 hours than i will finish it!

**Comment by FrozenKiller35** [comment] 2018-06-13 19:03
Updates Pulled and i added a fix for your latest update and a little cleanup ;) but for now still no event
Clean Server / Clean DB and New User :( 

There is no event for You to take a part in at the moment

**Comment by ghostfur** [comment] 2018-06-13 19:11
I Will check at the packet codes when home! Maby i have wrong Gf codes

**Comment by ghostfur** [comment] 2018-06-13 21:32
I did some cleaning i redownloading gameforge client now so i can work on the SM packets bytes and writes! so wait till iam done 💯

**Comment by ghostfur** [comment] 2018-06-14 15:30
What Version Client you guys using?

[VersionInfo]
GlobalVersion=187
DownloadIndex=0
LocalLevel=9
DownloadLevel=0

**Comment by benas80** [comment] 2018-06-14 15:36
I have newest version 187 (from GF)

**Comment by ghostfur** [comment] 2018-06-14 15:41
Thanks 50% downloading here! almost done than i will test on gameforge client instead of steam gameforge client for some people on my server it works and for some it dont so i asked around some people using GlobalVersion 185 so i will see if there is a difference first

**Comment by benas80** [comment] 2018-06-14 16:29
Is any chance to see working event window today ? :)

**Comment by ghostfur** [comment] 2018-06-14 16:45
Benas do you have a asmo or a elyos?

**Comment by benas80** [comment] 2018-06-14 16:45
I have Asmo characters.

**Comment by ghostfur** [comment] 2018-06-14 16:47
![16](https://user-images.githubusercontent.com/13853736/41426230-53ee7978-7003-11e8-83d2-4dd3469f65df.PNG)
Internet Slow for me today :(

**Comment by benas80** [comment] 2018-06-14 16:47
Almost finished :) Not bad

**Comment by ghostfur** [comment] 2018-06-14 16:49
Yes almost than i can test what it does !

**Comment by benas80** [comment] 2018-06-14 16:50
Good. Check these opcodes server->client and reversed.

**Comment by ghostfur** [comment] 2018-06-14 17:10
Yes i will do hope its almost done downloading

**Comment by FrozenKiller35** [comment] 2018-06-14 18:07
public void onLogout(Player player) {
        int remaining = player.getPlayerAccount().getId();

I think 99% of remaining  should be accountId
😉

**Comment by benas80** [comment] 2018-06-14 18:39
Did You test this AionGermany server files or You have other files?
We don't see this Icon "Event", probably server doesn't send right packet or wrong packet opcode when player enter the game.
Opcodes are the same as in Your files?
Check files please we are close to working :)

**Comment by ghostfur** [comment] 2018-06-14 18:48
I tested on AionGermany Server files yes to make sure and there its same like my own source

**Comment by ghostfur** [comment] 2018-06-14 18:50
Wait ill show you 👍

**Comment by benas80** [comment] 2018-06-14 18:52
![aion0001](https://user-images.githubusercontent.com/9912071/41431900-ac680874-7014-11e8-9e31-a41bf7ded7df.jpg)

Hmm. I have only this, new character with messed skills and not see Event Window Icon.

**Comment by ghostfur** [comment] 2018-06-14 18:53
You already choose class? because i have that but wont think it make difference haha but you never know

**Comment by benas80** [comment] 2018-06-14 18:54
No, just new character created.

**Comment by ghostfur** [comment] 2018-06-14 18:59
Iam really confused because you seen my screenshots and i using exactly same german source + emulator already made couple accounts and test chars and seems 90% is working for me haha!

**Comment by benas80** [comment] 2018-06-14 19:02
Is any config needed for this event window to enable ? (in aion launcher to ?)

**Comment by ghostfur** [comment] 2018-06-14 19:06
This is my bat file also there no config files for it also i tryed to make multiplay characters and they all have the event window screen 
start Bin64\aion.bin -ip:000.000.000.00 -port:2106 -cc:2 -lang:enu -noweb -noauthgg -f2p -megaphone -ingameshop -nowebshop

**Comment by benas80** [comment] 2018-06-14 19:11
I'll check Your bat file.

**Comment by benas80** [comment] 2018-06-14 19:19
No, still not working.

**Comment by ghostfur** [comment] 2018-06-14 19:57
Maby stupid question but is your character female?

**Comment by ghostfur** [comment] 2018-06-14 20:22
Amina - today on 22:19
ok on asmo female/male does not work, on ely it does work on male but not on female

Maby we can test this out?

**Comment by FrozenKiller35** [comment] 2018-06-14 21:48
-ip:000.000.000.00 ?????????

**Comment by ghostfur** [comment] 2018-06-15 04:48
Yes put your own ip haha

**Comment by ghostfur** [comment] 2018-06-15 04:49
I confirmed what Amina saying?

**Comment by Falke3434** [comment] 2018-06-15 22:35
Event Windows works only with new createt Chars, not with old Chars!

**Comment by benas80** [comment] 2018-06-16 06:02
Only Ely/Male working for me (showing Event Window).
New database and new chars.
Asmo working for You to ?

**Comment by ghostfur** [comment] 2018-06-16 10:33
Yo just woke up was a long night 🥇 haha for me it also only work on Ely/Male i check your new commits falke!

**Comment by Falke3434** [comment] 2018-06-16 11:09
Here a small Patch for the last Revision:

[EventWindow.zip](https://github.com/AionGermany/aion-germany/files/2108055/EventWindow.zip)

**Comment by benas80** [comment] 2018-06-16 11:21
Can You upgrade Your patch in source code Falke ?

**Comment by ghostfur** [comment] 2018-06-16 11:28
Thanks Falke Will Test It Out!

**Comment by benas80** [comment] 2018-06-17 06:07
Yes, working to all chars now but, we have 4 Events in config file,"Remaining Time" for them is 60,60,60,30 minutes, but ingame in Event Window i see all have 30 remaining minutes (exactly first three have 28 minutes after creating new player and enter to game).
What is exactly "Remaining opportunities to win" ? (where can we change this or not ?)

**Comment by ghostfur** [comment] 2018-06-17 09:20
Sorry for late response Frozen I do not have a lot of time this week but i will see what i can do 👍 
when i have some free time left :) we also need to get events_window.xml retail info not sure if marielle maby can parse it?

**Comment by ghostfur** [comment] 2018-06-17 10:15
Frozen i have tested your fix and its working! i need to find more information about how this event window orginally working and parse orginally event window.xml static data info so we can test it out!

**Comment by ghostfur** [comment] 2018-06-17 10:34
![timer](https://user-images.githubusercontent.com/13853736/41507060-a5ff04e8-722a-11e8-8a73-b4e4018c17e5.PNG)
What will happens after 6min 👍 we will see :)

**Comment by FrozenKiller35** [comment] 2018-06-17 12:41
Don't know where they come from yet but i think it should be possible to find those Bugs xD

**Comment by ghostfur** [comment] 2018-06-18 18:13
3. An Event window has been added that will show players what items they can obtain by remaining
logged in, and any requirements they have to meet such as level or subscription status

![download](https://user-images.githubusercontent.com/13853736/41554016-d6da458c-7333-11e8-8e5d-f34d836ca68d.jpg)

- The window displays immediately upon login. Click “Close this popup” to close it until the next day and
remove the HUD button.
- The window can be accessed by clicking the HUD button (only if “Close this popup” was not checked
today), or by going to Start Menu  Event.
- The window is only displayed if items are currently available.

**Comment by ghostfur** [comment] 2018-06-18 18:18
So i think it should give the item after the time is expired or something i trying to parse retail event window files now!

**Comment by ghostfur** [comment] 2018-06-18 18:44
So i think most of it works now i received the items couple min ago! so now i will try if i can parse some retail event_window.xml information!

**Comment by benas80** [comment] 2018-06-18 18:59
Did You checked if Your character have level 1 and event reward is between higher levels ? (45-65)
You shouldn't get reward.(i received even on level 1 character), check this Ghost please.

**Comment by ghostfur** [comment] 2018-06-18 19:00
Oow thanks benas80 so with lower lvl you also get the reward! good to know

**Comment by benas80** [comment] 2018-06-18 19:20
Yes, i You can try, this shouldn't be happend i think.

**Closed** 2018-06-26 23:19 UTC
